# --- !Ups

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;

USE `mydb`;

ALTER TABLE `appstore`.`products` ADD COLUMN `imageURL` VARCHAR(45) NULL DEFAULT NULL  AFTER `description` , ADD COLUMN `ProductVersion_id` INT(11) NOT NULL  AFTER `imageURL` , 
  ADD CONSTRAINT `fk_products_ProductVersion1`
  FOREIGN KEY (`ProductVersion_id` )
  REFERENCES `appstore`.`ProductVersion` (`id` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `fk_products_ProductVersion1` (`ProductVersion_id` ASC) ;

ALTER TABLE `appstore`.`users` DROP COLUMN `login` , DROP COLUMN `lastname` , DROP COLUMN `firstname` , ADD COLUMN `userId` VARCHAR(45) NOT NULL  AFTER `id` , ADD COLUMN `username` VARCHAR(80) NOT NULL  AFTER `userId` , ADD COLUMN `fullname` VARCHAR(50) NOT NULL  AFTER `username` , ADD COLUMN `email` VARCHAR(50) NOT NULL  AFTER `password` , ADD COLUMN `provider` VARCHAR(45) NOT NULL  AFTER `email` , ADD COLUMN `authmethod` VARCHAR(45) NULL DEFAULT NULL  AFTER `provider` 
, ADD UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) ;

ALTER TABLE `appstore`.`ProductVersion` 
DROP PRIMARY KEY 
, ADD PRIMARY KEY (`id`) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
